// Auto-generated. Do not edit!

// (in-package robot_arm_aansturing.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class positionResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.arrived = null;
    }
    else {
      if (initObj.hasOwnProperty('arrived')) {
        this.arrived = initObj.arrived
      }
      else {
        this.arrived = false;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type positionResult
    // Serialize message field [arrived]
    bufferOffset = _serializer.bool(obj.arrived, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type positionResult
    let len;
    let data = new positionResult(null);
    // Deserialize message field [arrived]
    data.arrived = _deserializer.bool(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 1;
  }

  static datatype() {
    // Returns string type for a message object
    return 'robot_arm_aansturing/positionResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'ea115e3ceb83b7b5fbcc7f283be1718c';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #result definition
    bool arrived
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new positionResult(null);
    if (msg.arrived !== undefined) {
      resolved.arrived = msg.arrived;
    }
    else {
      resolved.arrived = false
    }

    return resolved;
    }
};

module.exports = positionResult;
