// Generated by gencpp from file robot_arm_aansturing/command.msg
// DO NOT EDIT!


#ifndef ROBOT_ARM_AANSTURING_MESSAGE_COMMAND_H
#define ROBOT_ARM_AANSTURING_MESSAGE_COMMAND_H

#include <ros/service_traits.h>


#include <robot_arm_aansturing/commandRequest.h>
#include <robot_arm_aansturing/commandResponse.h>


namespace robot_arm_aansturing
{

struct command
{

typedef commandRequest Request;
typedef commandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct command
} // namespace robot_arm_aansturing


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_arm_aansturing::command > {
  static const char* value()
  {
    return "ff0e3fb9acee100884c63efa5d599c72";
  }

  static const char* value(const ::robot_arm_aansturing::command&) { return value(); }
};

template<>
struct DataType< ::robot_arm_aansturing::command > {
  static const char* value()
  {
    return "robot_arm_aansturing/command";
  }

  static const char* value(const ::robot_arm_aansturing::command&) { return value(); }
};


// service_traits::MD5Sum< ::robot_arm_aansturing::commandRequest> should match 
// service_traits::MD5Sum< ::robot_arm_aansturing::command > 
template<>
struct MD5Sum< ::robot_arm_aansturing::commandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_arm_aansturing::command >::value();
  }
  static const char* value(const ::robot_arm_aansturing::commandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_arm_aansturing::commandRequest> should match 
// service_traits::DataType< ::robot_arm_aansturing::command > 
template<>
struct DataType< ::robot_arm_aansturing::commandRequest>
{
  static const char* value()
  {
    return DataType< ::robot_arm_aansturing::command >::value();
  }
  static const char* value(const ::robot_arm_aansturing::commandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_arm_aansturing::commandResponse> should match 
// service_traits::MD5Sum< ::robot_arm_aansturing::command > 
template<>
struct MD5Sum< ::robot_arm_aansturing::commandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_arm_aansturing::command >::value();
  }
  static const char* value(const ::robot_arm_aansturing::commandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_arm_aansturing::commandResponse> should match 
// service_traits::DataType< ::robot_arm_aansturing::command > 
template<>
struct DataType< ::robot_arm_aansturing::commandResponse>
{
  static const char* value()
  {
    return DataType< ::robot_arm_aansturing::command >::value();
  }
  static const char* value(const ::robot_arm_aansturing::commandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_ARM_AANSTURING_MESSAGE_COMMAND_H
