// Generated by gencpp from file robot_arm_aansturing/position.msg
// DO NOT EDIT!


#ifndef ROBOT_ARM_AANSTURING_MESSAGE_POSITION_H
#define ROBOT_ARM_AANSTURING_MESSAGE_POSITION_H

#include <ros/service_traits.h>


#include <robot_arm_aansturing/positionRequest.h>
#include <robot_arm_aansturing/positionResponse.h>


namespace robot_arm_aansturing
{

struct position
{

typedef positionRequest Request;
typedef positionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct position
} // namespace robot_arm_aansturing


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_arm_aansturing::position > {
  static const char* value()
  {
    return "f2b13f7d6d2e580339acb0496be6fd7a";
  }

  static const char* value(const ::robot_arm_aansturing::position&) { return value(); }
};

template<>
struct DataType< ::robot_arm_aansturing::position > {
  static const char* value()
  {
    return "robot_arm_aansturing/position";
  }

  static const char* value(const ::robot_arm_aansturing::position&) { return value(); }
};


// service_traits::MD5Sum< ::robot_arm_aansturing::positionRequest> should match 
// service_traits::MD5Sum< ::robot_arm_aansturing::position > 
template<>
struct MD5Sum< ::robot_arm_aansturing::positionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_arm_aansturing::position >::value();
  }
  static const char* value(const ::robot_arm_aansturing::positionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_arm_aansturing::positionRequest> should match 
// service_traits::DataType< ::robot_arm_aansturing::position > 
template<>
struct DataType< ::robot_arm_aansturing::positionRequest>
{
  static const char* value()
  {
    return DataType< ::robot_arm_aansturing::position >::value();
  }
  static const char* value(const ::robot_arm_aansturing::positionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_arm_aansturing::positionResponse> should match 
// service_traits::MD5Sum< ::robot_arm_aansturing::position > 
template<>
struct MD5Sum< ::robot_arm_aansturing::positionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_arm_aansturing::position >::value();
  }
  static const char* value(const ::robot_arm_aansturing::positionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_arm_aansturing::positionResponse> should match 
// service_traits::DataType< ::robot_arm_aansturing::position > 
template<>
struct DataType< ::robot_arm_aansturing::positionResponse>
{
  static const char* value()
  {
    return DataType< ::robot_arm_aansturing::position >::value();
  }
  static const char* value(const ::robot_arm_aansturing::positionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_ARM_AANSTURING_MESSAGE_POSITION_H
