// Generated by gencpp from file robot_arm_aansturing/positionFeedback.msg
// DO NOT EDIT!


#ifndef ROBOT_ARM_AANSTURING_MESSAGE_POSITIONFEEDBACK_H
#define ROBOT_ARM_AANSTURING_MESSAGE_POSITIONFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_arm_aansturing
{
template <class ContainerAllocator>
struct positionFeedback_
{
  typedef positionFeedback_<ContainerAllocator> Type;

  positionFeedback_()
    : moving(false)  {
    }
  positionFeedback_(const ContainerAllocator& _alloc)
    : moving(false)  {
  (void)_alloc;
    }



   typedef uint8_t _moving_type;
  _moving_type moving;




  typedef boost::shared_ptr< ::robot_arm_aansturing::positionFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_arm_aansturing::positionFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct positionFeedback_

typedef ::robot_arm_aansturing::positionFeedback_<std::allocator<void> > positionFeedback;

typedef boost::shared_ptr< ::robot_arm_aansturing::positionFeedback > positionFeedbackPtr;
typedef boost::shared_ptr< ::robot_arm_aansturing::positionFeedback const> positionFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_arm_aansturing::positionFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_arm_aansturing::positionFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_arm_aansturing

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'robot_arm_aansturing': ['/home/nico/Documents/HAN/WoR World/Simulation/robot_simulation/application/devel/share/robot_arm_aansturing/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot_arm_aansturing::positionFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_arm_aansturing::positionFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_arm_aansturing::positionFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_arm_aansturing::positionFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_arm_aansturing::positionFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_arm_aansturing::positionFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_arm_aansturing::positionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9104f1a32b4fbf4d3c8c80d9b9493250";
  }

  static const char* value(const ::robot_arm_aansturing::positionFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9104f1a32b4fbf4dULL;
  static const uint64_t static_value2 = 0x3c8c80d9b9493250ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_arm_aansturing::positionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_arm_aansturing/positionFeedback";
  }

  static const char* value(const ::robot_arm_aansturing::positionFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_arm_aansturing::positionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#feedback\n\
bool moving\n\
\n\
";
  }

  static const char* value(const ::robot_arm_aansturing::positionFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_arm_aansturing::positionFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.moving);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct positionFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_arm_aansturing::positionFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_arm_aansturing::positionFeedback_<ContainerAllocator>& v)
  {
    s << indent << "moving: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.moving);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_ARM_AANSTURING_MESSAGE_POSITIONFEEDBACK_H
