; Auto-generated. Do not edit!


(cl:in-package robot_arm_aansturing-msg)


;//! \htmlinclude positionFeedback.msg.html

(cl:defclass <positionFeedback> (roslisp-msg-protocol:ros-message)
  ((moving
    :reader moving
    :initarg :moving
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass positionFeedback (<positionFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <positionFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'positionFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robot_arm_aansturing-msg:<positionFeedback> is deprecated: use robot_arm_aansturing-msg:positionFeedback instead.")))

(cl:ensure-generic-function 'moving-val :lambda-list '(m))
(cl:defmethod moving-val ((m <positionFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot_arm_aansturing-msg:moving-val is deprecated.  Use robot_arm_aansturing-msg:moving instead.")
  (moving m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <positionFeedback>) ostream)
  "Serializes a message object of type '<positionFeedback>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'moving) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <positionFeedback>) istream)
  "Deserializes a message object of type '<positionFeedback>"
    (cl:setf (cl:slot-value msg 'moving) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<positionFeedback>)))
  "Returns string type for a message object of type '<positionFeedback>"
  "robot_arm_aansturing/positionFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'positionFeedback)))
  "Returns string type for a message object of type 'positionFeedback"
  "robot_arm_aansturing/positionFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<positionFeedback>)))
  "Returns md5sum for a message object of type '<positionFeedback>"
  "9104f1a32b4fbf4d3c8c80d9b9493250")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'positionFeedback)))
  "Returns md5sum for a message object of type 'positionFeedback"
  "9104f1a32b4fbf4d3c8c80d9b9493250")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<positionFeedback>)))
  "Returns full string definition for message of type '<positionFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%bool moving~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'positionFeedback)))
  "Returns full string definition for message of type 'positionFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%bool moving~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <positionFeedback>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <positionFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'positionFeedback
    (cl:cons ':moving (moving msg))
))
