; Auto-generated. Do not edit!


(cl:in-package robot_arm_aansturing-msg)


;//! \htmlinclude positionResult.msg.html

(cl:defclass <positionResult> (roslisp-msg-protocol:ros-message)
  ((arrived
    :reader arrived
    :initarg :arrived
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass positionResult (<positionResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <positionResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'positionResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robot_arm_aansturing-msg:<positionResult> is deprecated: use robot_arm_aansturing-msg:positionResult instead.")))

(cl:ensure-generic-function 'arrived-val :lambda-list '(m))
(cl:defmethod arrived-val ((m <positionResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot_arm_aansturing-msg:arrived-val is deprecated.  Use robot_arm_aansturing-msg:arrived instead.")
  (arrived m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <positionResult>) ostream)
  "Serializes a message object of type '<positionResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'arrived) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <positionResult>) istream)
  "Deserializes a message object of type '<positionResult>"
    (cl:setf (cl:slot-value msg 'arrived) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<positionResult>)))
  "Returns string type for a message object of type '<positionResult>"
  "robot_arm_aansturing/positionResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'positionResult)))
  "Returns string type for a message object of type 'positionResult"
  "robot_arm_aansturing/positionResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<positionResult>)))
  "Returns md5sum for a message object of type '<positionResult>"
  "ea115e3ceb83b7b5fbcc7f283be1718c")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'positionResult)))
  "Returns md5sum for a message object of type 'positionResult"
  "ea115e3ceb83b7b5fbcc7f283be1718c")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<positionResult>)))
  "Returns full string definition for message of type '<positionResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%bool arrived~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'positionResult)))
  "Returns full string definition for message of type 'positionResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%bool arrived~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <positionResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <positionResult>))
  "Converts a ROS message object to a list"
  (cl:list 'positionResult
    (cl:cons ':arrived (arrived msg))
))
