(cl:defpackage robot_arm_aansturing-srv
  (:use )
  (:export
   "TEST"
   "<TEST-REQUEST>"
   "TEST-REQUEST"
   "<TEST-RESPONSE>"
   "TEST-RESPONSE"
   "COMMAND"
   "<COMMAND-REQUEST>"
   "COMMAND-REQUEST"
   "<COMMAND-RESPONSE>"
   "COMMAND-RESPONSE"
   "POSITION"
   "<POSITION-REQUEST>"
   "POSITION-REQUEST"
   "<POSITION-RESPONSE>"
   "POSITION-RESPONSE"
  ))

